//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoycoT_Virtual_ZPL_Printer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"^XA^MMT^PW812^LL1218^LS0^FO50,50^GB700,0,3^FS^FO50,50^GB0,150,3^FS^FO750,50^GB0,150,3^FS^FO50,200^GB700,0,3^FS^FO70,70^A0N,40,40^FDSHIP FROM:^FS^FO70,120^A0N,30,30^FDBoycoT Virtual Printer Co.^FS^FO70,160^A0N,30,30^FDTerry Olsen (den1tro)^FS^FO50,220^GB700,0,3^FS^FO50,220^GB0,200,3^FS^FO750,220^GB0,200,3^FS^FO50,420^GB700,0,3^FS^FO70,240^A0N,40,40^FDSHIP TO:^FS^FO70,290^A0N,35,35^FDJohn Smith^FS^FO70,335^A0N,30,30^FD123 Main Street^FS^FO70,375^A0N,30,30^FDBillings, MT 59101^FS^FO50,440^GB700,0,3^FS^FO50,440^GB0,280,3^FS^FO750,440^GB0,280,3^FS^FO50,720^GB700,0,3^FS^FO70,460^A0N,35,35^FDTRACKING NUMBER:^FS^FO70,510^BY3^BCN,100,Y,N,N^FD1Z999999999999999^FS^FO70,670^A0N,25,25^FDWeight: 2.5 lbs | Service: Ground^FS^FO50,740^GB700,0,3^FS^FO50,740^GB0,300,3^FS^FO750,740^GB0,300,3^FS^FO50,1040^GB700,0,3^FS^FO300,780^BQN,2,6^FDQA,https://track.example.com/1Z999999999999999^FS^FO70,1000^A0N,25,25^FDScan to track shipment^FS^FO50,1060^GB700,0,3^FS^FO50,1060^GB0,140,3^FS^FO750,1060^GB0,140,3^FS^FO50,1200^GB700,0,3^FS^FO70,1080^A0N,30,30^FDDate: 12/06/2025^FS^FO70,1120^A0N,30,30^FDOrder: #12345-ABC^FS^FO70,1160^A0N,25,25^FDPriority Delivery^FS^XZ")]
        public string TestLabel {
            get {
                return ((string)(this["TestLabel"]));
            }
        }
    }
}
